<?php

class Kanton {

    public function sort($field, $order = 'ASC') {
        // do not modify original array directly
        return Util::sort($this->cantons, $field, $order);
    }

    public function find($field, $value, $one) {
        $filtered = array_filter($this->cantons, function ($elem) use ($field, $value) { return $elem[$field] == $value; });
        if ($one) return empty($filtered) ? null : $filtered[0];
        else      return $filtered;
    }

    public function __call($name, $args) {
        if (strpos($name, 'sortBy', 0) === 0) {
            return $this->sort(ucfirst(substr($name, 6)), isset($args[0]) ? $args[0] : 'ASC');
        } else if (strpos($name, 'findBy', 0) === 0) {
            return $this->find(ucfirst(substr($name, 6)), $args[0], false);
        } else if (strpos($name, 'findOneBy', 0) === 0) {
            return $this->find(ucfirst(substr($name, 9)), $args[0], true);
        } else {
            trigger_error('Method ' . $name . ' does not exist!', E_USER_ERROR);    
        }
    }

    // Daten ganz unten zwecks uebersicht
    private $cantons = array(
        array (
            "Kuerzel" => "ZH",
            "Kanton" => "Zuerich",
            "Standesstimme" => "1",
            "Beitritt" => 1351,
            "Hauptort" => "Zuerich",
            "Einwohner 1" => "1'392'396",
            "Auslaender 2" => "24,9 %",
            "Flaeche 3" => "1'729",
            "Dichte 4" => "805",
            "Gemeinden 6" => 171,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "BE",
            "Kanton" => "Bern",
            "Standesstimme" => "1",
            "Beitritt" => 1353,
            "Hauptort" => "Bern",
            "Einwohner 1" => "985'046",
            "Auslaender 2" => "13,7 %",
            "Flaeche 3" => "5'959",
            "Dichte 4" => "165",
            "Gemeinden 6" => 382,
            "Amtssprache" => "deutsch, franzoesisch",
        ),
        array (
            "Kuerzel" => "LU",
            "Kanton" => "Luzern ",
            "Standesstimme" => "1",
            "Beitritt" => 1332,
            "Hauptort" => "Luzern",
            "Einwohner 1" => "381'966",
            "Auslaender 2" => "16,8 %",
            "Flaeche 3" => "1'493",
            "Dichte 4" => "256",
            "Gemeinden 6" => 87,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "UR",
            "Kanton" => "Uri ",
            "Standesstimme" => "1",
            "Beitritt" => 12917,
            "Hauptort" => "Altdorf",
            "Einwohner 1" => "35'382",
            "Auslaender 2" => "10,6 %",
            "Flaeche 3" => "1'077",
            "Dichte 4" => "33",
            "Gemeinden 6" => 20,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "SZ",
            "Kanton" => "Schwyz ",
            "Standesstimme" => "1",
            "Beitritt" => 12917,
            "Hauptort" => "Schwyz",
            "Einwohner 1" => "147'904",
            "Auslaender 2" => "19,3 %",
            "Flaeche 3" => "908",
            "Dichte 4" => "163",
            "Gemeinden 6" => 30,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "OW",
            "Kanton" => "Obwalden",
            "Standesstimme" => "0,5",
            "Beitritt" => 12917,
            "Hauptort" => "Sarnen",
            "Einwohner 1" => "35'878",
            "Auslaender 2" => "13,8 %",
            "Flaeche 3" => "491",
            "Dichte 4" => "73",
            "Gemeinden 6" => 7,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "NW",
            "Kanton" => "Nidwalden ",
            "Standesstimme" => "0,5",
            "Beitritt" => 12917,
            "Hauptort" => "Stans",
            "Einwohner 1" => "41'311",
            "Auslaender 2" => "12,4 %",
            "Flaeche 3" => "276",
            "Dichte 4" => "150",
            "Gemeinden 6" => 11,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "GL",
            "Kanton" => "Glarus ",
            "Standesstimme" => "1",
            "Beitritt" => 1352,
            "Hauptort" => "Glarus",
            "Einwohner 1" => "39'217",
            "Auslaender 2" => "21,6 %",
            "Flaeche 3" => "685",
            "Dichte 4" => "57",
            "Gemeinden 6" => 3,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "ZG",
            "Kanton" => "Zug ",
            "Standesstimme" => "1",
            "Beitritt" => 1352,
            "Hauptort" => "Zug",
            "Einwohner 1" => "115'104",
            "Auslaender 2" => "25,5 %",
            "Flaeche 3" => "239",
            "Dichte 4" => "482",
            "Gemeinden 6" => 11,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "FR",
            "Kanton" => "Freiburg ",
            "Standesstimme" => "1",
            "Beitritt" => 1481,
            "Hauptort" => "Freiburg",
            "Einwohner 1" => "284'668",
            "Auslaender 2" => "20,5 %",
            "Flaeche 3" => "1'671",
            "Dichte 4" => "170",
            "Gemeinden 6" => 165,
            "Amtssprache" => "franzoesisch, deutsch",
        ),
        array (
            "Kuerzel" => "SO",
            "Kanton" => "Solothurn ",
            "Standesstimme" => "1",
            "Beitritt" => 1481,
            "Hauptort" => "Solothurn",
            "Einwohner 1" => "257'393",
            "Auslaender 2" => "20,0 %",
            "Flaeche 3" => "791",
            "Dichte 4" => "325",
            "Gemeinden 6" => 120,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "BS",
            "Kanton" => "Basel-Stadt ",
            "Standesstimme" => "0,5",
            "Beitritt" => 1501,
            "Hauptort" => "Basel",
            "Einwohner 1" => "194'661",
            "Auslaender 2" => "34,1 %",
            "Flaeche 3" => "37",
            "Dichte 4" => "5'034",
            "Gemeinden 6" => 3,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "BL",
            "Kanton" => "Basel-Landschaft",
            "Standesstimme" => "0,5",
            "Beitritt" => 1501,
            "Hauptort" => "Liestal",
            "Einwohner 1" => "277'614",
            "Auslaender 2" => "19,9 %",
            "Flaeche 3" => "518",
            "Dichte 4" => "532",
            "Gemeinden 6" => 86,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "SH",
            "Kanton" => "Schaffhausen ",
            "Standesstimme" => "1",
            "Beitritt" => 1501,
            "Hauptort" => "Schaffhausen",
            "Einwohner 1" => "77'139",
            "Auslaender 2" => "24,2 %",
            "Flaeche 3" => "298",
            "Dichte 4" => "259",
            "Gemeinden 6" => 27,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "AR",
            "Kanton" => "Appenzell Ausserrhoden",
            "Standesstimme" => "0,5",
            "Beitritt" => 1513,
            "Hauptort" => "Herisau, Trogen5",
            "Einwohner 1" => "53'313",
            "Auslaender 2" => "14,5 %",
            "Flaeche 3" => "243",
            "Dichte 4" => "219",
            "Gemeinden 6" => 20,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "AI",
            "Kanton" => "Appenzell Innerrhoden",
            "Standesstimme" => "0,5",
            "Beitritt" => 1513,
            "Hauptort" => "Appenzell",
            "Einwohner 1" => "15'789",
            "Auslaender 2" => "9,9 %",
            "Flaeche 3" => "173",
            "Dichte 4" => "91",
            "Gemeinden 6" => 6,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "SG",
            "Kanton" => "St. Gallen",
            "Standesstimme" => "1",
            "Beitritt" => 1803,
            "Hauptort" => "St. Gallen",
            "Einwohner 1" => "483'156",
            "Auslaender 2" => "22,6 %",
            "Flaeche 3" => "2'026",
            "Dichte 4" => "239",
            "Gemeinden 6" => 85,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "GR",
            "Kanton" => "Graubuenden",
            "Standesstimme" => "1",
            "Beitritt" => 1803,
            "Hauptort" => "Chur",
            "Einwohner 1" => "193'388",
            "Auslaender 2" => "17,1 %",
            "Flaeche 3" => "7'105",
            "Dichte 4" => "27",
            "Gemeinden 6" => 176,
            "Amtssprache" => "deutsch, raetoromanisch, italienisch",
        ),
        array (
            "Kuerzel" => "AG",
            "Kanton" => "Aargau",
            "Standesstimme" => "1",
            "Beitritt" => 1803,
            "Hauptort" => "Aarau",
            "Einwohner 1" => "627'893",
            "Auslaender 2" => "22,9 %",
            "Flaeche 3" => "1'404",
            "Dichte 4" => "440",
            "Gemeinden 6" => 219,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "TG",
            "Kanton" => "Thurgau",
            "Standesstimme" => "1",
            "Beitritt" => 1803,
            "Hauptort" => "Frauenfeld",
            "Einwohner 1" => "251'973",
            "Auslaender 2" => "23,0 %",
            "Flaeche 3" => "991",
            "Dichte 4" => "254",
            "Gemeinden 6" => 80,
            "Amtssprache" => "deutsch",
        ),
        array (
            "Kuerzel" => "TI",
            "Kanton" => "Tessin",
            "Standesstimme" => "1",
            "Beitritt" => 1803,
            "Hauptort" => "Bellinzona",
            "Einwohner 1" => "336'943",
            "Auslaender 2" => "27,3 %",
            "Flaeche 3" => "2'812",
            "Dichte 4" => "120",
            "Gemeinden 6" => 147,
            "Amtssprache" => "italienisch",
        ),
        array (
            "Kuerzel" => "VD",
            "Kanton" => "Waadt",
            "Standesstimme" => "1",
            "Beitritt" => 1803,
            "Hauptort" => "Lausanne",
            "Einwohner 1" => "729'971",
            "Auslaender 2" => "32,2 %",
            "Flaeche 3" => "3'212",
            "Dichte 4" => "226",
            "Gemeinden 6" => 326,
            "Amtssprache" => "franzoesisch",
        ),
        array (
            "Kuerzel" => "VS",
            "Kanton" => "Wallis",
            "Standesstimme" => "1",
            "Beitritt" => 1815,
            "Hauptort" => "Sitten",
            "Einwohner 1" => "317'022",
            "Auslaender 2" => "22,0 %",
            "Flaeche 3" => "5'224",
            "Dichte 4" => "61",
            "Gemeinden 6" => 141,
            "Amtssprache" => "franzoesisch, deutsch",
        ),
        array (
            "Kuerzel" => "NE",
            "Kanton" => "Neuenburg ",
            "Standesstimme" => "1",
            "Beitritt" => 1815,
            "Hauptort" => "Neuenburg",
            "Einwohner 1" => "173'183",
            "Auslaender 2" => "24,4 %",
            "Flaeche 3" => "803",
            "Dichte 4" => "216",
            "Gemeinden 6" => 53,
            "Amtssprache" => "franzoesisch",
        ),
        array (
            "Kuerzel" => "GE",
            "Kanton" => "Genf",
            "Standesstimme" => "1",
            "Beitritt" => 1815,
            "Hauptort" => "Genf",
            "Einwohner 1" => "473'941",
            "Auslaender 2" => "37,0 %",
            "Flaeche 3" => "282",
            "Dichte 4" => "1'633",
            "Gemeinden 6" => 45,
            "Amtssprache" => "franzoesisch",
        ),
        array (
            "Kuerzel" => "JU",
            "Kanton" => "Jura ",
            "Standesstimme" => "1",
            "Beitritt" => 1979,
            "Hauptort" => "Delsberg",
            "Einwohner 1" => "70'542",
            "Auslaender 2" => "13,0 %",
            "Flaeche 3" => "838",
            "Dichte 4" => "84",
            "Gemeinden 6" => 64,
            "Amtssprache" => "franzoesisch",
        ),
    );
}
