Vagrant.configure("2") do |config| 
	config.vm.box = "precise64"
	config.vm.provision :shell, :path => "bootstrap.sh"
	config.vm.network "forwarded_port", guest: 80, host: 8080
        config.vm.synced_folder ".", "/var/www", mount_options: ["dmode=777","fmode=777"]
end
